version: '3.8'

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80/tcp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - /usr/share/nginx/html
      - ./my-proxy.conf:/etc/nginx/conf.d/my-proxy.conf:ro
    networks:
      - nginx-proxy